on:
  push:
  pull_request_target:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ env.SSH_KEY }}
          access_token: ${{ env.GH_TOKEN }}
          sot_repo: Juanito98/test
          destination_repo: Juanito98/test2
